Neos:
  Flow:
    mvc:
      routes:
        'MIWeb.Neos.Blog':
          position: 'before Neos.Neos'
  Neos:
    nodeTypes:
      groups:
        blog:
          position: 'after plugins'
          label: Blog
    fusion:
      autoInclude:
        MIWeb.Neos.Blog: true
